# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 86e8025ee71bd07f6320dec03c983cbb418848ca92dae43297f365f84a7815169426cc48f5dd590456d0e4539c682f63731cf19d987136b3b731aa9147a94c6f

test:
  secret_key_base: e3f93118f2d662ec196981ec7725b18b9e8d3b9bcb65053e3a25349dc4bb79cfb5c9d6b25d93d554509fc574837fac1f8c5235d3c82c1c7fe49315db3d87d4a3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
